// Generated by gencpp from file motor/MotorRPM.msg
// DO NOT EDIT!


#ifndef MOTOR_MESSAGE_MOTORRPM_H
#define MOTOR_MESSAGE_MOTORRPM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motor
{
template <class ContainerAllocator>
struct MotorRPM_
{
  typedef MotorRPM_<ContainerAllocator> Type;

  MotorRPM_()
    : rpm_left(0.0)
    , rpm_right(0.0)  {
    }
  MotorRPM_(const ContainerAllocator& _alloc)
    : rpm_left(0.0)
    , rpm_right(0.0)  {
  (void)_alloc;
    }



   typedef float _rpm_left_type;
  _rpm_left_type rpm_left;

   typedef float _rpm_right_type;
  _rpm_right_type rpm_right;





  typedef boost::shared_ptr< ::motor::MotorRPM_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motor::MotorRPM_<ContainerAllocator> const> ConstPtr;

}; // struct MotorRPM_

typedef ::motor::MotorRPM_<std::allocator<void> > MotorRPM;

typedef boost::shared_ptr< ::motor::MotorRPM > MotorRPMPtr;
typedef boost::shared_ptr< ::motor::MotorRPM const> MotorRPMConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motor::MotorRPM_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motor::MotorRPM_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motor::MotorRPM_<ContainerAllocator1> & lhs, const ::motor::MotorRPM_<ContainerAllocator2> & rhs)
{
  return lhs.rpm_left == rhs.rpm_left &&
    lhs.rpm_right == rhs.rpm_right;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motor::MotorRPM_<ContainerAllocator1> & lhs, const ::motor::MotorRPM_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::motor::MotorRPM_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor::MotorRPM_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor::MotorRPM_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor::MotorRPM_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor::MotorRPM_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor::MotorRPM_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motor::MotorRPM_<ContainerAllocator> >
{
  static const char* value()
  {
    return "811f89cd5e54718d6b2167dcea919c32";
  }

  static const char* value(const ::motor::MotorRPM_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x811f89cd5e54718dULL;
  static const uint64_t static_value2 = 0x6b2167dcea919c32ULL;
};

template<class ContainerAllocator>
struct DataType< ::motor::MotorRPM_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motor/MotorRPM";
  }

  static const char* value(const ::motor::MotorRPM_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motor::MotorRPM_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Represents the RPM value of the left and right motors 0...1\n"
"float32 rpm_left\n"
"float32 rpm_right\n"
;
  }

  static const char* value(const ::motor::MotorRPM_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motor::MotorRPM_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rpm_left);
      stream.next(m.rpm_right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorRPM_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motor::MotorRPM_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motor::MotorRPM_<ContainerAllocator>& v)
  {
    s << indent << "rpm_left: ";
    Printer<float>::stream(s, indent + "  ", v.rpm_left);
    s << indent << "rpm_right: ";
    Printer<float>::stream(s, indent + "  ", v.rpm_right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOR_MESSAGE_MOTORRPM_H
